apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service-ext
  annotations:
    service.beta.kubernetes.io/azure-dns-label-name: workflow-manager-rabbit-mq
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 15672
  selector:
    app: rabbit-mq
    loadBalancerIP: 51.138.114.97