apiVersion: v1
data:
  SA_PASSWORD: WW91cl9wYXNzd29yZDEyMw==
kind: Secret
metadata:
  labels:
    env: dev
  name: identity-service-mssql-secret
  namespace: default
type: Opaque
---
apiVersion: v1
data:
  SA_PASSWORD: WW91cl9wYXNzd29yZDEyMw==
kind: Secret
metadata:
  labels:
    env: dev
  name: processes-service-mssql-secret
  namespace: default
type: Opaque
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/azure-dns-label-name: workflow-manager-identity-service
  labels:
    env: dev
  name: identity-service-api-service-ext
spec:
  loadBalancerIP: 51.124.86.253
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: identity-service-api
    env: dev
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  labels:
    env: dev
  name: identity-service-mssql-service
spec:
  ports:
  - port: 1433
    protocol: TCP
    targetPort: 1433
  selector:
    app: identity-service-mssql
    env: dev
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/azure-dns-label-name: workflow-manager-processes-service
  labels:
    env: dev
  name: processes-service-api-service-ext
spec:
  loadBalancerIP: 51.124.86.254
  ports:
  - port: 80
  selector:
    app: processes-service-api
    env: dev
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  labels:
    env: dev
  name: processes-service-mssql-service
spec:
  ports:
  - port: 1433
    protocol: TCP
    targetPort: 1433
  selector:
    app: processes-service-mssql
    env: dev
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    env: dev
  name: rabbitmq-service
spec:
  ports:
  - port: 5672
    protocol: TCP
  selector:
    app: rabbit-mq
    env: dev
  type: ClusterIP
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    app: identity-service-api
    env: dev
  name: identity-service-api-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: identity-service-api
      env: dev
  template:
    metadata:
      labels:
        app: identity-service-api
        env: dev
      name: identity-service-api
    spec:
      containers:
      - env:
        - name: ConnectionStrings__MsSqlDatabase
          value: Data Source=$(MSSQL_SERVICE_NAME);User ID=sa;Password=$(MSSQL_SERVICE_SECRET);Connect
            Timeout=30;Encrypt=False;TrustServerCertificate=False;ApplicationIntent=ReadWrite;MultiSubnetFailover=False
        - name: ASPNETCORE_ENVIRONMENT
          value: Docker
        - name: ASPNETCORE_BASE_LOG_DIR
          value: ../var/log/identity-service-api
        image: workflowmanager.azurecr.io/workflow-manager-identity-service-api:latest
        name: identity-service-api
        volumeMounts:
        - mountPath: /var/log/identity-service-api
          name: identity-service-api-logs
      volumes:
      - hostPath:
          path: /var/log/containers
        name: identity-service-api-logs
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    app: identity-service-mssql
    env: dev
  name: identity-service-mssql-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: identity-service-mssql
      env: dev
  template:
    metadata:
      labels:
        app: identity-service-mssql
        env: dev
      name: identity-service-mssql
    spec:
      containers:
      - env:
        - name: ACCEPT_EULA
          value: "Y"
        - name: SA_PASSWORD
          valueFrom:
            secretKeyRef:
              key: SA_PASSWORD
              name: identity-service-mssql-secret
        image: microsoft/mssql-server-linux
        name: identity-service-mssql
        ports:
        - containerPort: 1433
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    app: processes-service-api
    env: dev
  name: processes-service-api-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: processes-service-api
      env: dev
  template:
    metadata:
      labels:
        app: processes-service-api
        env: dev
      name: processes-service-api
    spec:
      containers:
      - env:
        - name: ConnectionStrings__MsSqlDatabase
          value: Data Source=$(MSSQL_SERVICE_NAME);User ID=sa;Password=$(MSSQL_SERVICE_SECRET);Connect
            Timeout=30;Encrypt=False;TrustServerCertificate=False;ApplicationIntent=ReadWrite;MultiSubnetFailover=False
        - name: ASPNETCORE_ENVIRONMENT
          value: Docker
        - name: ASPNETCORE_BASE_LOG_DIR
          value: ../var/log/processes-service-api
        - name: RabbitMq__Hostname
          value: rabbitmq-service
        image: latest
        name: processes-service-api
        volumeMounts:
        - mountPath: /var/log/processes-service-api
          name: processes-service-api-logs
      volumes:
      - hostPath:
          path: /var/log/containers
        name: processes-service-api-logs
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    app: processes-service-mssql
    env: dev
  name: processes-service-mssql-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: processes-service-mssql
      env: dev
  template:
    metadata:
      labels:
        app: processes-service-mssql
        env: dev
      name: processes-service-mssql
    spec:
      containers:
      - env:
        - name: ACCEPT_EULA
          value: "Y"
        - name: SA_PASSWORD
          valueFrom:
            secretKeyRef:
              key: SA_PASSWORD
              name: processes-service-mssql-secret
        image: microsoft/mssql-server-linux
        name: processes-service-mssql
        ports:
        - containerPort: 1433
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    app: rabbitmq
    env: dev
  name: rabbit-mq-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbit-mq
      env: dev
  template:
    metadata:
      labels:
        app: rabbit-mq
        env: dev
      name: rabbit-mq
    spec:
      containers:
      - command:
        - rabbitmq-server
        image: rabbitmq:3-management
        name: rabbit-mq
