version: '3.4'
services:
  workflowmanager.processservice.api:
    image: wojcikmm/workflow-manager-process-service-api
    ports:
      - "8000:80"
    environment:
      ASPNETCORE_ENVIRONMENT: "Docker"
    depends_on:
      - workflowmanager.rabbitmq
      - workflowmanager.processservice.db
    links:
      - workflowmanager.rabbitmq
      - workflowmanager.processservice.db
    restart: on-failure

  workflowmanager.processservice.db:
    image: "microsoft/mssql-server-linux"
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"
    ports:
      - "1453:1433"
      - "1454:1434"

  workflowmanager.statusservice.api:
    image: wojcikmm/workflow-manager-status-service-api
    ports:
      - "9000:80"
    environment:
      ASPNETCORE_ENVIRONMENT: "Docker"
    depends_on:
      - workflowmanager.rabbitmq
      - workflowmanager.statusservice.db
    links:
      - workflowmanager.rabbitmq
      - workflowmanager.statusservice.db
    restart: on-failure

  workflowmanager.statusservice.db:
    image: "microsoft/mssql-server-linux"
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"
    ports:
      - "1463:1433"
      - "1464:1434"



  workflowmanager.rabbitmq:
    image: "rabbitmq:3-management"
    command: rabbitmq-server
    hostname: "rabbitmq"
    ports:
      - "8001:15672"
      - "5652:5672"
    labels:
      NAME: "rabbitmq"