version: '3.4'
services:
  workflowmanager.apigateway:
    image: wojcikmm/workflow-manager-api-gateway
    build:
      context: .
      dockerfile: src/WorkflowManager.APIGateway/Dockerfile
    ports:
      - "8000:80"
    environment:
      ASPNETCORE_ENVIRONMENT: "Docker"
    depends_on:
      - workflowmanager.processservice.api
      - workflowmanager.statusservice.api
    links:
      - workflowmanager.processservice.api
      - workflowmanager.statusservice.api
    restart: on-failure

  workflowmanager.processservice.api:
    image: wojcikmm/workflow-manager-process-service-api
    build:
      context: .
      dockerfile: src/Services/ProcessService/WorkflowManager.ProcessService.API/Dockerfile
    ports:
      - "8001:80"
    environment:
      ASPNETCORE_ENVIRONMENT: "Docker"
    depends_on:
      - workflowmanager.rabbitmq
      - workflowmanager.processservice.db
    links:
      - workflowmanager.rabbitmq
      - workflowmanager.processservice.db
    restart: on-failure

  workflowmanager.processservice.db:
    image: "microsoft/mssql-server-linux"
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"
    ports:
      - "1453:1433"
      - "1454:1434"

  workflowmanager.statusservice.api:
    image: wojcikmm/workflow-manager-status-service-api
    build:
      context: .
      dockerfile: src/Services/StatusService/WorkflowManager.StatusService.API/Dockerfile
      args:
        rabbit_port: 5672
    ports:
      - "8002:80"
    environment:
      ASPNETCORE_ENVIRONMENT: "Docker"
    depends_on:
      - workflowmanager.rabbitmq
      - workflowmanager.statusservice.db
    links:
      - workflowmanager.rabbitmq
      - workflowmanager.statusservice.db
    restart: on-failure

  workflowmanager.statusservice.db:
    image: "microsoft/mssql-server-linux"
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"
    ports:
      - "1463:1433"
      - "1464:1434"

  workflowmanager.rabbitmq:
    image: "rabbitmq:3-management"
    command: rabbitmq-server
    hostname: "rabbitmq"
    ports:
      - "15672:15672"
      - "5652:5672"
    labels:
      NAME: "rabbitmq"