version: '3.4'
services:
  process_service_api:
    build:
      context: ./src
      dockerfile: ProcessService.Dockerfile
      args:
        rabbit_port: 5672
    ports:
      - "8000:80"
    depends_on:
      - rabbitmq
      - process_service_db
    links:
      - rabbitmq
      - process_service_db
    restart: on-failure

   process_service_db:
    image: "microsoft/mssql-server-linux"
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"
    ports:
      - "1453:1433"
      - "1454:1434"

  rabbitmq:
    image: "rabbitmq:3-management"
    command: rabbitmq-server
    hostname: "rabbitmq"
    ports:
      - "15672:15672"
      - "5672:5672"
    labels:
      NAME: "rabbitmq"
