version: '3.4'
services:
  # RABBIT MQ (PORT: 15672)
  workflowmanager.rabbitmq:
    image: "rabbitmq:3-management"
    command: rabbitmq-server
    hostname: "rabbitmq"
    ports:
      - "15672:15672"
      - "5652:5672"
    labels:
      NAME: "rabbitmq"

  # IDENTITY SERVICE (PORT: 5000)
  workflowmanager.identityservice.api:
    image: "${DOCKER_HUB_LOGIN}/workflow-manager-identity-service-api"
    build:
      context: src/Services/IdentityService/WorkflowManager.IdentityService.API
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
    depends_on:
      - workflowmanager.identityservice.db
    restart: on-failure

  workflowmanager.identityservice.db:
    image: "microsoft/mssql-server-linux"
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"
    ports:
      - "1443:1433"
      - "1444:1434"


  # API GATEWAY (PORT: 8000)
  workflowmanager.gateway.api:
    image: ${DOCKER_HUB_LOGIN}/workflow-manager-gateway-api
    build:
      context: src/Services/GatewayService/WorkflowManager.OcelotGatewayService.API
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    environment:
      ASPNETCORE_ENVIRONMENT: "${ENVIRONMENT}"
    depends_on:
      - workflowmanager.processservice.api
      - workflowmanager.statusservice.api
      - workflowmanager.operationsservice.api
      - workflowmanager.identityservice.api

    restart: on-failure


  # PROCESS SERVICE (PORT: 8001)
  workflowmanager.processservice.api:
    image: "${DOCKER_HUB_LOGIN}/workflow-manager-process-service-api"
    build:
      context: .
      dockerfile: src/Services/ProcessService/WorkflowManager.ProcessService.API/Dockerfile
    ports:
      - "8001:80"
    environment:
      ASPNETCORE_ENVIRONMENT: "${ENVIRONMENT}"
    depends_on:
      - workflowmanager.rabbitmq
      - workflowmanager.processservice.db
    restart: on-failure

  workflowmanager.processservice.db:
    image: "microsoft/mssql-server-linux"
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"
    ports:
      - "1453:1433"
      - "1454:1434"


  #STATUS SERVICE (PORT: 8002)
  workflowmanager.statusservice.api:
    image: "${DOCKER_HUB_LOGIN}/workflow-manager-status-service-api"
    build:
      context: .
      dockerfile: src/Services/StatusService/WorkflowManager.StatusService.API/Dockerfile
      args:
        rabbit_port: 5672
    ports:
      - "8002:80"
    environment:
      ASPNETCORE_ENVIRONMENT: "${ENVIRONMENT}"
    depends_on:
      - workflowmanager.rabbitmq
      - workflowmanager.statusservice.db
    restart: on-failure

  workflowmanager.statusservice.db:
    image: "microsoft/mssql-server-linux"
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"
    ports:
      - "1463:1433"
      - "1464:1434"


  # OPERATIONS SERVICE(PORT: 8003)
  workflowmanager.operationsservice.api:
    image: "${DOCKER_HUB_LOGIN}/workflow-manager-operations-service-api"
    build:
      context: .
      dockerfile: src/Services/OperationsService/WorkflowManager.OperationsService.API/Dockerfile
    ports:
      - "8003:80"
    environment:
      ASPNETCORE_ENVIRONMENT: "${ENVIRONMENT}"
    depends_on:
      - workflowmanager.rabbitmq
    restart: on-failure
