apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2020-05-09T11:50:50Z"
  generateName: processes-service-mssql-deployment-c54d46bbf-
  labels:
    app: processes-service-mssql
    env: dev
    pod-template-hash: c54d46bbf
  name: processes-service-mssql-deployment-c54d46bbf-rqj9r
  namespace: default
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: processes-service-mssql-deployment-c54d46bbf
    uid: 395b6d5b-e71c-48e7-a85b-49d8f81f4742
  resourceVersion: "222955"
  selfLink: /api/v1/namespaces/default/pods/processes-service-mssql-deployment-c54d46bbf-rqj9r
  uid: e5801a5d-2cb5-4cae-8a16-dd413e66d3d0
spec:
  containers:
  - env:
    - name: ACCEPT_EULA
      value: "Y"
    - name: SA_PASSWORD
      valueFrom:
        secretKeyRef:
          key: SA_PASSWORD
          name: processes-service-mssql-secret
    image: microsoft/mssql-server-linux
    imagePullPolicy: Always
    name: mssql
    ports:
    - containerPort: 1433
      protocol: TCP
    resources:
      limits:
        cpu: 300m
        memory: 3200m
      requests:
        cpu: 100m
        memory: 100m
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-44fc6
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: docker-desktop
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: default-token-44fc6
    secret:
      defaultMode: 420
      secretName: default-token-44fc6
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2020-05-09T11:50:50Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2020-05-09T11:50:50Z"
    message: 'containers with unready status: [mssql]'
    reason: ContainersNotReady
    status: "False"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2020-05-09T11:50:50Z"
    message: 'containers with unready status: [mssql]'
    reason: ContainersNotReady
    status: "False"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2020-05-09T11:50:50Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - image: microsoft/mssql-server-linux
    imageID: ""
    lastState: {}
    name: mssql
    ready: false
    restartCount: 0
    state:
      waiting:
        reason: ContainerCreating
  hostIP: 192.168.65.3
  phase: Pending
  qosClass: Burstable
  startTime: "2020-05-09T11:50:50Z"
