apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity-service-api-deployment
  namespace: default
  labels:
    app: identity-service-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: identity-service-api
  template:
    metadata:
      name: identity-service-api
      labels:
        app: identity-service-api
    spec:
      containers:
        - name: identity-service-api
          image: workflowmanager.azurecr.io/workflow-manager-identity-service-api
          imagePullPolicy: IfNotPresent
          resources:
              requests:
                cpu: 100m
                memory: 100m
              limits:
                cpu: 200m
                memory: 200M
          env:
            - name: ConnectionStrings__MsSqlDatabase
              valueFrom:
                secretKeyRef:
                  name: connection-strings-secrets
                  key: identity-mssql
            - name: ASPNETCORE_ENVIRONMENT
              value: Docker
            - name: ASPNETCORE_BASE_LOG_DIR
              value: ../var/log/identity-service-api
          volumeMounts:
            - name: identity-service-api-logs
              mountPath: /var/log/identity-service-api
      volumes:
        - name: identity-service-api-logs
          hostPath:
            path: /var/log/containers
