apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: identity-service-api-deployment
  namespace: default
  labels:
    app: identity-service-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: identity-service-api
  template:
    metadata:
      name: identity-service-api
      labels:
        app: identity-service-api
    spec:
      containers:
        - name: identity-service-api
          image: workflowmanager.azurecr.io/workflow-manager-identity-service-api
          resources:
              requests:
                cpu: 100m
                memory: 100m
              limits:
                cpu: 200m
                memory: 500M
          env:
            - name: ConnectionStrings__MsSqlDatabase
              value: "Data Source=$(MSSQL_SERVICE_NAME);User ID=sa;Password=$(MSSQL_SERVICE_SECRET);Connect Timeout=30;Encrypt=False;TrustServerCertificate=False;ApplicationIntent=ReadWrite;MultiSubnetFailover=False"
            - name: ASPNETCORE_ENVIRONMENT
              value: Docker
            - name: ASPNETCORE_BASE_LOG_DIR
              value: ../var/log/identity-service-api
          volumeMounts:
            - name: identity-service-api-logs
              mountPath: /var/log/identity-service-api
      volumes:
        - name: identity-service-api-logs
          hostPath:
            path: /var/log/containers
