apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: processes-service-mssql-deployment
  namespace: default
  labels:
    app: processes-service-mssql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: processes-service-mssql
  template:
    metadata:
      name: processes-service-mssql
      labels:
        app: processes-service-mssql
    spec:
      containers:
        - name: processes-service-mssql
          image: microsoft/mssql-server-linux
          resources:
              requests:
                cpu: 100m
                memory: 100m
              limits:
                cpu: 300m
                memory: 3G
          ports:
            - containerPort: 1433
          env:
            - name: ACCEPT_EULA
              value: "Y"
            - name: SA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: processes-service-mssql-secret
                  key: SA_PASSWORD
          volumeMounts:
            - name: processes-service-mssql-persistent-storage
              mountPath: /var/opt/mssql
      volumes:
        - name: processes-service-mssql-persistent-storage
          persistentVolumeClaim:
            claimName: processes-service-mssql-volume