apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: -mssql-deployment
  namespace: default
  labels:
    app: -mssql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: -mssql
  template:
    metadata:
      name: mssql
      labels:
        app: -mssql
    spec:
      containers:
        - name: mssql
          image: microsoft/mssql-server-linux
          resources:
              requests:
                cpu: 100m
                memory: 100m
              limits:
                cpu: 100m
                memory: 200m
          ports:
            - containerPort: 1433
          env:
            - name: ACCEPT_EULA
              value: "Y"
            - name: SA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: -mssql-secret
                  key: SA_PASSWORD