bases:
  - identity-service
  - processes-service
  - rabbit-mq
vars:
  - name: RABBITMQ_SERVICE_NAME
    objref:
      kind: Service
      name: rabbitmq-service
      apiVersion: v1
    fieldref:
      fieldpath: metadata.name