# Identity Service Database
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: identity-service-mssql-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
---
apiVersion: v1
kind: Secret
metadata:
  name: identity-service-mssql-secret
  namespace: default
type: Opaque
data:
  SA_PASSWORD: WW91cl9wYXNzd29yZDEyMw==
---
apiVersion: v1
kind: Service
metadata:
  name: identity-service-mssql-service-spec
spec:
  selector:
    app: identity-service-mssql
  ports:
    - protocol: TCP
      port: 1433
      targetPort: 1433
  type: LoadBalancer
  # loadBalancerIP: 51.138.108.217

---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: identity-service-mssql-deployment-spec
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: identity-service-mssql
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: identity-service-mssql
          image: microsoft/mssql-server-linux
          ports:
            - containerPort: 1433
          env:
            - name: ACCEPT_EULA
              value: "Y"
            - name: SA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: identity-service-mssql-secret
                  key: SA_PASSWORD
          volumeMounts:
            - name: identity-service-mssql-persistent-storage
              mountPath: /var/opt/mssql
      volumes:
        - name: identity-service-mssql-persistent-storage
          persistentVolumeClaim:
            claimName: identity-service-mssql-claim
---
# Web API
apiVersion: v1
kind: Service
metadata:
  name: identity-service-api-service-spec
  annotations:
    service.beta.kubernetes.io/azure-dns-label-name: workflow-manager-identity-service-api
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
  selector:
    app: identity-service-api
  loadBalancerIP: 51.124.75.161
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: identity-service-api-deployment-spec
  namespace: default
  labels:
    app: identity-service-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: identity-service-api
  template:
    metadata:
      name: identity-service-api
      labels:
        app: identity-service-api
    spec:
      containers:
        - name: identity-service-api
          image: workflowmanager.azurecr.io/workflow-manager-identity-service-api:latest
          imagePullPolicy: "Always"
          env:
            - name: ConnectionStrings__MsSqlDatabase
              value: "Data Source=identity-service-mssql-service-spec;User ID=sa;Password=Your_password123;Connect Timeout=30;Encrypt=False;TrustServerCertificate=False;ApplicationIntent=ReadWrite;MultiSubnetFailover=False"
            - name: ASPNETCORE_ENVIRONMENT
              value: Development

