kind: Service
apiVersion: v1
metadata:
  name: rabbitmq-service-spec
spec:
  selector:
    app:  rabbitmq
  type:  LoadBalancer
  ports:
  - port: 5672
  - port: 15672
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: rabbitmq-deployment-spec
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:3-management
          ports:
            - containerPort: 5672
            - containerPort: 15672