version: '3.4'
services:
  workflowmanager.identityservice.api:
    image: "workflowmanager.azurecr.io/workflow-manager-identity-service-api"
    build:
      context: ../src
      dockerfile: Services/IdentityService/WorkflowManager.IdentityService.API/Dockerfile
    ports:
      - "8081:80"
    environment:
      ASPNETCORE_ENVIRONMENT: "Docker"
    depends_on:
      - workflowmanager.identityservice.db
    restart: on-failure

  workflowmanager.identityservice.db:
    image: "microsoft/mssql-server-linux"
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"
