apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity-service-mssql-deployment
  namespace: default
  labels:
    app: identity-service-mssql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: identity-service-mssql
  template:
    metadata:
      name: identity-service-mssql
      labels:
        app: identity-service-mssql
    spec:
      containers:
        - name: identity-service-mssql
          image: microsoft/mssql-server-linux
          ports:
            - containerPort: 1433
          env:
            - name: ACCEPT_EULA
              value: "Y"
            - name: SA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: identity-service-mssql-secret
                  key: SA_PASSWORD