apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: rabbit-mq-deployment
  namespace: default
  labels:
    app: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbit-mq
  template:
    metadata:
      name: rabbit-mq
      labels:
        app: rabbit-mq
    spec:
      containers:
        - name: rabbit-mq
          image: rabbitmq:3-management
          command:
            - rabbitmq-server
          ports:
            - containerPort: 5672
          env:
            - name: RABBITMQ_DEFAULT_USER
              value: user
            - name: RABBITMQ_DEFAULT_PASS
              value: user