apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbit-mq-deployment
  namespace: default
  labels:
    app: rabbit-mq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbit-mq
  template:
    metadata:
      name: rabbit-mq
      labels:
        app: rabbit-mq
    spec:
      containers:
        - name: rabbit-mq
          image: rabbitmq:3-management
          command:
            - rabbitmq-server
            - "ls /etc/rabbitmq"
          ports:
            - containerPort: 5672
          volumeMounts:
            - mountPath: /etc/rabbitmq/rabbitmq.conf
              name: rabbitmq-config
              subPath: rabbitmq.conf
          # env:
            # - name: RABBITMQ_DEFAULT_USER
            #   value: user
            # - name: RABBITMQ_DEFAULT_PASS
            #   value: user
            # - name: RABBITMQ_NODENAME
            #   value: rabbitmq-service
            # - name: K8S_SERVICE_NAME
            #   value: rabbitmq-service
      volumes:
        - name:  rabbitmq-config
          configMap:
            name: rabbitmq-config-map