apiVersion: apps/v1
kind: Deployment
metadata:
  name: processes-service-api-deployment
  namespace: default
  labels:
    app: processes-service-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: processes-service-api
  template:
    metadata:
      name: processes-service-api
      labels:
        app: processes-service-api
    spec:
      containers:
        - name: processes-service-api
          image: workflowmanager.azurecr.io/workflow-manager-processes-service-api
          imagePullPolicy: IfNotPresent
          resources:
              requests:
                cpu: 100m
                memory: 100m
              limits:
                cpu: 200m
                memory: 200M
          env:
            - name: ConnectionStrings__MsSqlDatabase
              valueFrom:
                secretKeyRef:
                  name: connection-strings-secrets
                  key: processes-mssql
            - name: ASPNETCORE_ENVIRONMENT
              value: Docker
            - name: ASPNETCORE_BASE_LOG_DIR
              value: ../var/log/processes-service-api
            - name: RabbitMq__Hostname
              value: $(RABBITMQ_SERVICE_NAME)
            - name: RabbitMq__Username
              value: guest
            - name: RabbitMq__Password
              value: guest
          volumeMounts:
            - name: processes-service-api-logs
              mountPath: /var/log/processes-service-api
      volumes:
        - name: processes-service-api-logs
          hostPath:
            path: /var/log/containers
